from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent

CORE_DIR = PROJECT_ROOT / "core"
DATA_DIR = PROJECT_ROOT / "data"
MODELS_DIR = PROJECT_ROOT / "models"
AUDIO_DIR = DATA_DIR / "audio"

WAKE_WORD = "jarvis"

SAMPLE_RATE = 16000
CHANNELS = 1

WAKE_WINDOW_SECONDS = 3.5
COMMAND_WINDOW_SECONDS = 12.0

WHISPER_MODEL = "base.en"

TTS_RATE = 185
TTS_VOLUME = 1.0